#URL to JSON file
jsonlist: ChangeMe!

#Time between checks back to the JSON file
refreshtime: 5

#Parameter to set results to return from JSON for processing. Setting this lower will improve performance but at the risk of missing donations.
#If the donations per second is greater than the buffer/refreshtime donations will be missed.
buffersize: 25

#Minimum donation requested to get whitelisted (integer)
min_donation: 20

#Child's Play API Details
event_id: none
api_key: none
api_secret: none