name: ImRaising
version: 0.1
description: A Minecraft plugin that utilizes the ImRaising JSON API to parse donations.
author: Matthew Salsamendi

main: com.mcprohosting.plugins.imraising.ImRaising
database: false

commands:
   imraising:
     description: Managment commands for ImRaising
     permission: inferno.flagrate
     usage: Syntax error! Type /imraising help for command reference.
permissions:
   imraising.*:
     description: Gives access to all ImRaising commands
     children:
       imraising.parsenow: true