name: Mindcrack-Marathon-Donations
version: 0.1
description: A Minecraft plugin that utilizes a JSON stream to parse donations.
author: Matthew Salsamendi

main: com.mcprohosting.plugins.donations.Donations
database: false